GoLocal/Models/User.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace GoLocal.Models
{
    public class User
    {
        public int ID { get; set; }
        [Required]
        [EmailAddress]
        [MaxLength(50)]
        public string Email { get; set; }
        [StringLength(100)]
        public string Name { get; set; }
        [Display(Name = "Registration Date")]
        [DisplayFormat(DataFormatString = "{0:MM/dd/yyyy hh:mm tt}", ApplyFormatInEditMode = true)]
        public DateTime? RegDate { get; set; }
        [Display(Name = "Date Of Birth")]
        [DisplayFormat(DataFormatString = "{0:MM/dd/yyyy}", ApplyFormatInEditMode = true)]
        public DateTime? DateOfBirth { get; set; }
        [StringLength(12)]
        [Display(Name = "Phone Number")]
        [RegularExpression("[0-9]{1,12}")]
        public string PhoneNumber { get; set; }
        [StringLength(1)]
        public string Status { get; set; }
        public virtual List<Feed> MyFeeds { get; set; }
        public virtual List<Comment> MyComments { get; set; }
        public virtual List<Vote> MyVotes { get; set; }

        public User()
        {
            MyFeeds = new List<Feed>();
            MyComments = new List<Comment>();
            MyVotes = new List<Vote>();
        }
    }
}

GoLocal/Controllers/FeedsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using GoLocal.Models;
using GoLocal.Util;
using System.Net.Http;
using Newtonsoft.Json;

namespace GoLocal.Controllers
{
    public class FeedsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Feeds
        public async Task<ActionResult> Index(string latLng)
        {
            var feedList = db.FeedList.Include(f => f.User);
            if (!User.IsInRole("Admin"))
            {
                feedList = feedList.Where(f => f.Status == "A");
            }
            if (!string.IsNullOrEmpty(latLng))
            {
                string location = await AppUtil.GetMapData(latLng);
                ViewBag.weather = await AppUtil.GetWeatherData(latLng);
                feedList = feedList.Where(f => f.LocationName == location).OrderByDescending(f => f.Timestamp).Take(10);
            }
            else
            {
                feedList = feedList.OrderByDescending(f => f.Timestamp).Take(10);
            }
            return View(await feedList.ToListAsync());
        }

        // GET: Feeds
        public async Task<ActionResult> Search(string email, string startDate, string endDate, string term, string zipCode, int page = 0)
        {
            var feedList = db.FeedList.Include(f => f.User);
            bool searchCompleted = false;
            if (!string.IsNullOrWhiteSpace(email))
            {
                feedList = feedList.Where(f => f.User.Email.ToLower() == email.ToLower());
                searchCompleted = true;
            }
            if (!string.IsNullOrWhiteSpace(startDate))
            {
                try
                {
                    DateTime date = DateTime.Parse(startDate);
                    feedList = feedList.Where(f => f.Timestamp >= date);
                    searchCompleted = true;
                }
                catch (Exception e)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest, e.Message);
                }
            }
            if (!string.IsNullOrWhiteSpace(endDate))
            {
                try
                {
                    DateTime date = DateTime.Parse(endDate);
                    feedList = feedList.Where(f => f.Timestamp <= date);
                    searchCompleted = true;
                }
                catch (Exception e)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest, e.Message);
                }
            }
            if (!string.IsNullOrWhiteSpace(term))
            {
                feedList = feedList.Where(f => f.Title.ToLower().Contains(term.ToLower()));
                searchCompleted = true;
            }
            if (!string.IsNullOrWhiteSpace(zipCode))
            {
                feedList = feedList.Where(f => f.LocationName.ToLower().Contains(zipCode.ToLower()));
                searchCompleted = true;
            }
            if (searchCompleted)
            {
                int pageSize = 5;
                int count = feedList.Count();
                List<Feed> feeds = await feedList.OrderByDescending(f => f.Timestamp).Skip(pageSize * page).Take(pageSize).ToListAsync();
                ViewBag.SearchParams = string.Join(",",email,startDate,endDate,term,zipCode);
                this.ViewBag.MaxPage = (count / pageSize) - (count % pageSize == 0 ? 1 : 0);
                this.ViewBag.Page = page;
                return View(feeds);
            }
            else
            {
                return View(new List<Feed>());
            }
        }

        // GET: Feeds/Details/5
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Feed feed = await db.FeedList.FindAsync(id);
            if (feed == null)
            {
                return HttpNotFound();
            }
            return View(feed);
        }

        // GET: Feeds/Create
        [Authorize]
        public ActionResult Create()
        {
            return View();
        }

        // POST: Feeds/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        public async Task<ActionResult> Create([Bind(Include = "ID,Title,Content,TimeStamp,UserID,LocationName,Lat,Long")] Feed feed)
        {
            User user = db.UserList.Where(u => u.Email.ToLower() == User.Identity.Name.ToLower()).ToList()[0];
            if (user.Status == "I")
            {
                ModelState.AddModelError("", "User is inactive!");
            }
            if (feed.Lat == 0 && feed.Long == 0)
            {
                ModelState.AddModelError("", "Please allow location access!");
            }
            if (ModelState.IsValid)
            {
                feed.UserID = user.ID;
                feed.Timestamp = DateTime.Now;
                feed.LocationName = await AppUtil.GetMapData(feed.Lat + "," + feed.Long);
                feed.Status = "A";
                db.FeedList.Add(feed);
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }

            return View(feed);
        }

        // GET: Feeds/Edit/5
        [Authorize]
        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Feed feed = await db.FeedList.FindAsync(id);
            if (feed == null || feed.User.Email.ToLower() != User.Identity.Name.ToLower())
            {
                return HttpNotFound();
            }
            return View(feed);
        }

        // POST: Feeds/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        public async Task<ActionResult> Edit([Bind(Include = "ID,Title,Content,TimeStamp,UserID,LocationName,Lat,Long")] Feed feed)
        {
            Feed storedFeed = await db.FeedList.FindAsync(feed.ID);
            if (storedFeed == null || storedFeed.User.Email.ToLower() != User.Identity.Name.ToLower())
            {
                return HttpNotFound();
            }
            if (ModelState.IsValid)
            {
                storedFeed.Title = feed.Title;
                storedFeed.Content = feed.Content;
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return View(feed);
        }

        // GET: Feeds/Delete/5
        [Authorize]
        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Feed feed = await db.FeedList.FindAsync(id);
            if (feed == null || feed.User.Email.ToLower() != User.Identity.Name.ToLower())
            {
                return HttpNotFound();
            }
            return View(feed);
        }

        // POST: Feeds/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            Feed feed = await db.FeedList.FindAsync(id);
            feed.Status = "I";
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

GoLocal/Controllers/VotesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using GoLocal.Models;

namespace GoLocal.Controllers
{
    public class VotesController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Votes
        public async Task<ActionResult> Index(int page = 0)
        {
            var voteList = db.VoteList.Include(v => v.Feed).Include(v => v.User);
            if (!User.IsInRole("Admin"))
            {
                voteList = voteList.Where(v => v.User.Email.ToLower() == User.Identity.Name.ToLower());
            }
            int pageSize = 5;
            int count = voteList.Count();
            List<Vote> votes = await voteList.OrderByDescending(v => v.Timestamp).Skip(page * pageSize).Take(pageSize).ToListAsync();
            this.ViewBag.MaxPage = (count / pageSize) - (count % pageSize == 0 ? 1 : 0);
            this.ViewBag.Page = page;
            return View(votes);
        }

        // GET: Votes/Details/5
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Vote vote = await db.VoteList.FindAsync(id);
            if (vote == null)
            {
                return HttpNotFound();
            }
            return View(vote);
        }

        // GET: Votes/Create
        public async Task<ActionResult> Upvote(int? feedId)
        {
            if (feedId == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            User user = db.UserList.Where(u => u.Email.ToLower() == User.Identity.Name.ToLower()).ToList()[0];
            if (user.Status == "I")
            {
                ModelState.AddModelError("", "User is inactive!");
            }
            Feed feed = await db.FeedList.FindAsync(feedId);
            if (feed == null || feed.Status != "A")
            {
                ModelState.AddModelError("", "Feed is inactive!");
            }
            int count = db.VoteList.Where(v => v.Feed.ID == feedId && v.User.Email.ToLower() == User.Identity.Name.ToLower()).Count();
            if (count > 0)
            {
                ModelState.AddModelError("", "User has already voted!");
            }
            if (ModelState.IsValid)
            {
                Vote vote = new Vote();
                vote.FeedID = feed.ID;
                vote.Type = "U";
                vote.Timestamp = DateTime.Now;
                vote.UserID = user.ID;
                db.VoteList.Add(vote);
                await db.SaveChangesAsync();
            }

            return RedirectToAction("Details", "Feeds", routeValues: new { id = feed.ID });
        }

        // POST: Votes/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        public async Task<ActionResult> Downvote(int? feedId)
        {
            if(feedId == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            User user = db.UserList.Where(u => u.Email.ToLower() == User.Identity.Name.ToLower()).ToList()[0];
            if (user.Status == "I")
            {
                ModelState.AddModelError("", "User is inactive!");
            }
            Feed feed = await db.FeedList.FindAsync(feedId);
            if (feed == null || feed.Status != "A")
            {
                ModelState.AddModelError("", "Feed is inactive!");
            }
            int count = db.VoteList.Where(v => v.Feed.ID == feedId && v.User.Email.ToLower() == User.Identity.Name.ToLower()).Count();
            if(count > 0)
            {
                ModelState.AddModelError("", "User has already voted!");
            }
            int totalCount = db.VoteList.Where(v => v.FeedID == feedId).Count();
            int downVote = db.VoteList.Where(v => v.FeedID == feedId && v.Type == "D").Count();
            if(totalCount <= 10 && downVote >= 6)
            {
                feed.Status = "I";
            }
            if (ModelState.IsValid)
            {
                Vote vote = new Vote();
                vote.FeedID = feed.ID;
                vote.Type = "D";
                vote.Timestamp = DateTime.Now;
                vote.UserID = user.ID;
                db.VoteList.Add(vote);
                await db.SaveChangesAsync();
            }

            return RedirectToAction("Details", "Feeds", routeValues: new { id = feed.ID });
        }

        // GET: Votes/Delete/5
        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Vote vote = await db.VoteList.FindAsync(id);
            if (vote == null || vote.User.Email.ToLower() != User.Identity.Name.ToLower())
            {
                return HttpNotFound();
            }
            return View(vote);
        }

        // POST: Votes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            Vote vote = await db.VoteList.FindAsync(id);
            if(vote == null || vote.User.Email.ToLower() != User.Identity.Name.ToLower())
            {
                return HttpNotFound();
            }
            db.VoteList.Remove(vote);
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

GoLocal/Views/Users/Create.cshtml
@model GoLocal.Models.User

@{
    ViewBag.Title = "Create User";
}

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Create User</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        
        <div class="form-group">
            @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DateOfBirth, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DateOfBirth, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DateOfBirth, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PhoneNumber, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PhoneNumber, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PhoneNumber, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

GoLocal/Views/Users/Delete.cshtml
@model GoLocal.Models.User

@{
    ViewBag.Title = "Delete User";
}

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Delete User</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Email)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DateOfBirth)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DateOfBirth)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.RegDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.RegDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PhoneNumber)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PhoneNumber)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Status)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Status)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

GoLocal/Views/Users/Details.cshtml
@model GoLocal.Models.User

@{
    ViewBag.Title = "User Details";
}

<div>
    <h4>User Details</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Email)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DateOfBirth)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DateOfBirth)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.RegDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.RegDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PhoneNumber)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PhoneNumber)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Status)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Status)
        </dd>

    </dl>
    <p>
        @Html.ActionLink("Edit", "Edit", new { id = Model.ID }) |
        @Html.ActionLink("Back to List", "Index")
    </p>

    @if (Model.MyFeeds.Count > 0)
    {
        <h4>My Recent Feeds</h4>
        <table class="table">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.MyFeeds[0].Title)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.MyFeeds[0].Timestamp)
            </th>
            <th>
                Upvote
            </th>
            <th>
                Downvote
            </th>
            <th></th>
        </tr>

        @foreach (var item in Model.MyFeeds.Take(5))
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Title)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Timestamp)
                </td>
                <td>
                    @item.Upvote()
                </td>
                <td>
                    @item.Downvote()
                </td>
                <td>
                    @Html.ActionLink("Edit", "Edit", "Feeds", new { id = item.ID }, new { }) |
                    @Html.ActionLink("Details", "Details", "Feeds", new { id = item.ID }, new { }) |
                    @Html.ActionLink("Delete", "Delete", "Feeds", new { id = item.ID }, new { })
                </td>
            </tr>
        }

    </table>
    }

    @if (Model.MyComments.Count > 0)
    {
        <h4>My Recent Comments</h4>
        <table class="table">
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.MyComments[0].Feed.Title)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.MyComments[0].Timestamp)
                </th>
                <th></th>
            </tr>

            @foreach (var item in Model.MyComments.Take(5))
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.Feed.Title)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Timestamp)
                    </td>
                    <td>
                        @Html.ActionLink("Edit", "Edit", "Comments", new { id = item.ID }, new { }) |
                        @Html.ActionLink("Details", "Details", "Comments", new { id = item.ID }, new { }) |
                        @Html.ActionLink("Delete", "Delete", "Comments", new { id = item.ID }, new { })
                    </td>
                </tr>
            }

        </table>
    }

    @if (Model.MyVotes.Count > 0)
    {
        <h4>My Recent Comments</h4>
        <table class="table">
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.MyVotes[0].Feed.Title)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.MyVotes[0].Timestamp)
                </th>
                <th></th>
            </tr>

            @foreach (var item in Model.MyVotes.Take(5))
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.Feed.Title)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Timestamp)
                    </td>
                    <td>
                        @Html.ActionLink("Edit", "Edit", "Votes", new { id = item.ID }, new { }) |
                        @Html.ActionLink("Details", "Details", "Votes", new { id = item.ID }, new { }) |
                        @Html.ActionLink("Delete", "Delete", "Votes", new { id = item.ID }, new { })
                    </td>
                </tr>
            }

        </table>
    }
</div>

GoLocal/Views/Users/Edit.cshtml
@model GoLocal.Models.User

@{
    ViewBag.Title = "Edit User";
}

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Edit User</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ID)

        <div class="form-group">
            @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control readonly", @readonly = "readonly" } })
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DateOfBirth, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DateOfBirth, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DateOfBirth, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PhoneNumber, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PhoneNumber, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PhoneNumber, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

GoLocal/Views/Users/Index.cshtml
@model IEnumerable<GoLocal.Models.User>

@{
    ViewBag.Title = "View Users";
}

<h4>View Users</h4>
<hr />
@if (Model.Count() > 0)
{
    <table class="table">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Email)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DateOfBirth)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.RegDate)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.PhoneNumber)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Status)
            </th>
            <th></th>
        </tr>

        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Email)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.DateOfBirth)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.RegDate)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.PhoneNumber)
                </td>
                <td>
                    @if (item.Status == "A")
                    {
                        <span class="badge" style="background-color: #5cb85c;">&nbsp;</span>
                    }
                    else
                    {
                        <span class="badge" style="background-color: #d9534f;">&nbsp;</span>
                    }
                </td>
                <td>
                    @Html.ActionLink("Edit", "Edit", new { id = item.ID }) |
                    @Html.ActionLink("Details", "Details", new { id = item.ID }) |
                    @Html.ActionLink("Delete", "Delete", new { id = item.ID })
                </td>
            </tr>
        }
    </table>
    if (ViewBag.Page > 0)
    {
        <a href="@Url.Action("Index", new { page = ViewBag.Page - 1 })"
           class="btn btn-default">
            &laquo; Prev
        </a>
    }
    if (ViewBag.Page < ViewBag.MaxPage)
    {
        <a href="@Url.Action("Index", new { page = ViewBag.Page + 1 })"
           class="btn btn-default">
            Next &raquo;
        </a>
    }
}